apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lingoda-ebs
  labels:
    app: lingoda-demo
    stage: dev
    version: 7.0.1
  annotations:
    author: "ciprian.bucur"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer