apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-webserver
  labels:
    app: lingoda-demo
    role: php-webserver-deploy
    stage: dev
    version: 7.0.1
  annotations:
    author: "ciprian.bucur"
spec:
  selector:
    matchLabels:
      app: lingoda-demo
      role: php-webserver-pod
      stage: dev
      version: 7.0.1
  replicas: 1
  template:
    metadata:
      labels:
        app: lingoda-demo    
        role: php-webserver-pod
        stage: dev
        version: 7.0.1
      annotations:
        author: "ciprian.bucur"
    spec:
      securityContext:
        fsGroup: 33
      containers:
      - name: webserver
        image: cipribucur/lingoda-webserver:latest
        imagePullPolicy: Always
        env:
        - name: NGINX_ROOT_PATH
          value: "/var/www/lingoda/public/"
        resources:
          requests:
            memory: 250Mi
          limits:
            memory: 250Mi
        ports:
        - name: webserver-http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: "/etc/nginx/templates/lingoda.conf.template"
          subPath: lingoda.conf.template
        - name: public
          mountPath: "/var/www/lingoda/public"
        - name: var
          mountPath: "/var/www/lingoda/var"
      - name: php-fpm
        image: cipribucur/lingoda-php:1.0.6
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: "db-svc"
        - name: DB_DATABASE
          value: "lingoda"
        - name: DB_USERNAME
          value: "lingoda"
        - name: DB_PORT
          value: "3306"
        - name: APP_ENV
          value: "prod"
        - name: APP_DEBUG
          value: "0"
        - name: DB_PASSWORD
          value: "lingoda"
        - name: OPCACHE_JIT_BUFFER_SIZE
          value: "0"
        resources:
          requests:
            memory: 300Mi
          limits:
            memory: 300Mi
        volumeMounts:
        - name: public
          mountPath: "/var/www/lingoda/public"
        - name: var
          mountPath: "/var/www/lingoda/var"
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:33 /var/www/lingoda/public /var/www/lingoda/var"]
          volumeMounts:
          - name: public
            mountPath: "/var/www/lingoda/public"
          - name: var
            mountPath: "/var/www/lingoda/var"
        - name: init-lingoda
          command: ['/bin/bash', "/var/www/lingoda/bin/init.sh"]
          image: cipribucur/lingoda-php:1.0.6
          imagePullPolicy: Always
          env:
          - name: DB_HOST
            value: "db-svc"
          - name: DB_DATABASE
            value: "lingoda"
          - name: DB_USERNAME
            value: "lingoda"
          - name: DB_PORT
            value: "3306"
          - name: APP_ENV
            value: "prod"
          - name: APP_DEBUG
            value: "0"
          - name: DB_PASSWORD
            value: "lingoda"
          - name: OPCACHE_JIT_BUFFER_SIZE
            value: "0"
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 300Mi
          volumeMounts:
          - name: public
            mountPath: "/var/www/lingoda/public"
          - name: var
            mountPath: "/var/www/lingoda/var"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: public
        emptyDir: {}
      - name: var
        emptyDir: {}
