apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: lingoda-demo    
    stage: dev
    version: 7.0.1
  annotations:
    author: "ciprian.bucur"
data:
  lingoda.conf.template: |-
    server {
        listen 80;
        server_name lingoda.local;
        root ${NGINX_ROOT_PATH};
        
        index index.php;

        location / {
            try_files $uri /index.php$is_args$args;
        }
        location ~ ^/index\.php(/|$) {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $document_root;
            internal;
        }
        location ~ \.php$ {
            return 404;
        }
        access_log  /proc/self/fd/2;
        error_log   /proc/self/fd/2 warn;
    }