apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public
  labels:
    app: lingoda-demo    
    stage: dev
    version: 7.0.1
  annotations:
    author: "ciprian.bucur"
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
  storageClassName: standard