apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: lingoda-demo    
    stage: dev
    version: 7.0.1
  annotations:
    author: "ciprian.bucur"
data:
  my.cnf: |-
    [mysqld]
    default-authentication-plugin=mysql_native_password
    default-time-zone = "+00:00"
    disable_log_bin
    log_bin_trust_function_creators = 1
    innodb_buffer_pool_size=1G
    #innodb_force_recovery = 1