apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  labels:
    app: lingoda-demo    
    stage: dev
    version: 7.0.1
  annotations:
    author: "ciprian.bucur"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: standard