apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loadbalancer
  labels:
    app: lingoda-demo    
    stage: dev
    version: 7.0.1
  annotations:
    author: "ciprian.bucur"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - lingoda.inocentium.work
    secretName: cert
  rules:
    - host: lingoda.inocentium.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: php-webserver-svc
                port:
                  name: webserver-http
      