apiVersion: v1
kind: ConfigMap
metadata:
  name: supervisor-config
  labels:
    app: lingoda-demo    
    stage: dev
    version: 7.0.1
  annotations:
    author: "ciprian.bucur"
data:
  supervisord.conf: |-
    [supervisord]
    nodaemon=true

    [supervisorctl]

    [program:messenger-consumer-core]
    command=php /var/www/lingoda/bin/console messenger:consume lingoda_core -vv --memory-limit=250M --time-limit=1800
    numprocs=1
    startsecs=0
    autostart=true
    autorestart=true
    process_name=%(program_name)s_%(process_num)02d
    stdout_logfile=/proc/self/fd/2
    stdout_logfile_maxbytes=0
    redirect_stderr=true

    [program:entrypoint]
    command=/var/www/lingoda/bin/entrypoint.sh
    autorestart=false

    [program:cron]
    command=/etc/init.d/cron start
    autostart=true
    autorestart=true
    redirect_stderr=true
    startretries=0
    stdout_logfile=/proc/self/fd/2
    stdout_logfile_maxbytes=0
    stderr_logfile=/proc/self/fd/2
    stderr_logfile_maxbytes=0