apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db
spec:
  encryptedData:
    DB_PASSWORD: AgBAf6SXs3eDJEgRx3HEve8/thOdjXoKNZjY+OvfRSCcVAQ28Zk86hQ+/fzkwuTh+OOb19SH17gdJAp7uAeHTSNX1LlLVy8kC+lmOhYYpffuHfTTgqu41/EwwvegzzcTkWHBZ+8+Yacj4zWk/nep7uThM1TyDt5CVgm414+W7tdeHebB54TSFybDRINN4pYiihPLgL6GcbfqhngvaEwPEcFCkjbVi/bQvvEB/exWHXEYOUv+lid56vlb6a6RvWLFm6OkVQSe9fljoM4lFZcc6o35+uB6lDf1h3DaXw9H5ahdztx9ZIddam+G5c87FGU8rRcU63WYScNCrIlOzw8QVNlXSl5lnD4wVfbbXAO84Ic4/ms3rsz58PM2s0cSBz1rAFedICWPQkRzd+Ei7AnujYYB3PhjhA1CiZIveyQQivb1wW9sSD3TiWEKGD2wIsCvyOz8E6TDdhAcxwlaLYLT4/Gim52+kcxN5OxRsWuYAPgedHPLMBmWQhgLomy7xkZoe6y3Qek4/V2QChaWoIMNV/ZTf8c/HXWizhEFV3nMfCiupqQ/xcv2B7mPkXtK+9yjSt4+AwQ3zAgXHeB536w1d4cI8Z/US5rGJFQndHQ74HSC1CHHal9+4pVbqR8GZALSe0KYmzf5Ym0Y/c19iVFtuFp0Doa2Bv8T7Yo/erbLjp4isp/mI82muOnBPRKOcXUg9HpcoxK9sta8mRT87Qpy
    MYSQL_ROOT_PASSWORD: AgBcHQMcdOqBN8g77YR8Boe20Fm4QIPBpMlPtQEiHOEfLk4vV5WvvOtgL98zu1G8fJXPAmWedr+mLd1StAgLtsWfqgSHM/YB0lsLIYR/t1LGx9ojQ0ikvtWxXak9dMQs9JnYWE2G9NHtXlC29HXOogwhEDWeMzh5GuFsIajm2vHyGRz38U6g4L+nVX7DC60rpQ7rMVYS9L7UwX/1zso6PbpzPW/VmP4N5SFXhkq3eOW4/77TrdNEF8zHHL42SUMNVAR4PIzt5mUuYJ4L8WLj8w+g8+no1kI0RFgnVeWByKsugEiw0CiKOcgV7vyNeWj/jPq4YzTsJgmTZ7cOp1YJfcMlVsFXcyOqg9hn1dIvp8+gmaOKBQu25qmz8Ft3vFN0fUTpRcMuSGK6j4/3gM4rWZ7V3RzTADoZ+BMye46Y4yCv6KMlGP/fNogjYZpLgKVB5kJDl8kDoXO5HC3ndTtinPFLUBHPnnOc+vmuqwInzBIyV/mjHE0MvzArj07O8+7v6rtymb9jBhNdAf1xqSVEl3qSI/2U3YN1JjQc1WIg2kN/vcvl/ZLMrlvqcO+62ih6ZCYDyeknh4acyYzInohmkJiA9lmAl40Bc+ARRAfeHk8uoZ4JVInAMhcVUsAcuSAXaKscpfTdPmyDafyYi9f/ek6gZuipSmBnVRZ53xt4gpNogNtDnnWgkA33Tn5CO2PtzBrNFkLBV9QlMmfzpDLpZFdzpw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: db

